my_string = input('тут должен быть текст: ')
print('длина строки: ',len(my_string))
print('строка в верхнем регистре: ',my_string.upper())
print('строка в нижнем регистре: ',my_string.lower())
print('строка без пробелов: ',my_string.replace(' ',''))
print('первый символ: ',my_string[0])
print('последний символ: ',my_string[-1])